stellar:
  is_testnet: true

horizon:
  endpoint: http://horizon
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4" # Issuer of assets

payment:
  target_address: "GADWZB6QUUJCX4OA2KEXIYR7ZGHUJB2ZI5OM3NXTP65VBW727MBIRM6F" # Payment sender address

deposit:
  asset_owner: "GBA4EX43M25UPV4WIE6RRMQOFTWXZZRIPFAI5VPY6Z2ZVVXVWZ6NEOOB"
  asset_issuer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"

log:
  level: debug
  disable_sentry: true

