horizon:
  endpoint: "http://horizon"
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"

withdraw:
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"
  owner: "GBA4EX43M25UPV4WIE6RRMQOFTWXZZRIPFAI5VPY6Z2ZVVXVWZ6NEOOB"

rpc:
  endpoint: "https://ropsten.infura.io/v3/0137951ef58c40dd95f418fe046f98d3"

transfer:
  seed: "75603080DAED3924A5544F6815688A2E94F07C89864BFB750D99A8F107B8E3E8"
  address: "0x9266798B4469275e844C94f747b4e35Dc6aD8D77"
  confirmations: 3
  gas_limit: 1200000
  gas_price: 80

log:
  level: debug
  disable_sentry: true
