stellar:
  is_testnet: true

horizon:
  endpoint: 'http://horizon'
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4" # Issuer of assets

payment:
  source_signer: "SCJSL6NUTWF6JT45DXUQM3BNGTOKYJ2QR5LE5C2QVQM5BXWKSNAYQYN3" # Payment sender signer
  source_address: "GADWZB6QUUJCX4OA2KEXIYR7ZGHUJB2ZI5OM3NXTP65VBW727MBIRM6F" # Payment sender address

withdraw:
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"
  owner: "GBA4EX43M25UPV4WIE6RRMQOFTWXZZRIPFAI5VPY6Z2ZVVXVWZ6NEOOB"

log:
  level: debug
  disable_sentry: true

